### ISSUE TITLE
images w/ Jolokia (eg) fabric8/java-jboss-openjdk8-jdk:1.0.10 don't work well with wf swarm

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/base-images#10]
there is some collision when jolokia is enabled and trying to use wildfly swarm:

> ```
>     ... 11 more
> ```
> 
> Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"
>         at org.jboss.as.logging.LoggingExtension.initialize(LoggingExtension.java:147)
>         at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:131)
>         at org.jboss.as.controller.extension.ExtensionAddHandler.initializeExtension(ExtensionAddHandler.java:104)
>         at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:144)
>         at org.jboss.as.controller.extension.ParallelExtensionAddHandler$ExtensionInitializeTask.call(ParallelExtensionAddHandler.java:127)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
>         at org.jboss.threads.JBossThread.run(JBossThread.java:320)

Apr 04, 2016 10:44:55 PM org.jboss.as.server.ServerService boot
FATAL: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:84)
        at org.wildfly.swarm.bootstrap.Main.run(Main.java:48)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:43)
Caused by: java.util.concurrent.ExecutionException: Operation failed
        at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
        at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
        at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:113)
        at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:216)
        at org.wildfly.swarm.container.Container.start(Container.java:260)
        at org.wildfly.swarm.Swarm.simpleMain(Swarm.java:72)
        at org.wildfly.swarm.Swarm.main(Swarm.java:65)
        ... 7 more
Caused by: java.lang.Exception: WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
        at org.jboss.as.server.BootstrapListener.bootFailure(BootstrapListener.java:87)
        at org.jboss.as.server.ServerService.boot(ServerService.java:384)
        at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)

**Comment by christian-posta** [comment]
Can work around by disabling Jolokia w/ environment variable

AB_JOLOKIA_OFF=true

**Comment by rafabene** [comment]
Interesting. I was able to make it work in CDK 2.0Beta5, and WildFly Beta7. Check it out: https://github.com/redhat-helloworld-msa/hola

**Comment by rafabene** [comment]
It seems that's an issue with WildFly Swarm Beta6. I had to downgrade WFSwarm and now I have the same issue of @christian-posta . I reported it at https://issues.jboss.org/browse/SWARM-462

**Comment by rhuss** [comment]
That's an ongoing issue with Jolokia on Wildfly (AS and Swarm). See https://github.com/rhuss/jolokia/issues/258 and also https://issues.jboss.org/browse/SWARM-204

'hope we can fix that soon.
